### ISSUE TITLE
compile error?

### ISSUE THREAD

**Issue by TheHatMan98** [sub1to/subVersion_2#3]
![capture](https://cloud.githubusercontent.com/assets/25558904/26516978/d9dd89c2-428f-11e7-900c-dacfebf07059.PNG)

**Comment by sub1to** [comment]
Search engines are your friend.
https://stackoverflow.com/questions/6568188/how-can-i-solve-this-error

**Comment by TheHatMan98** [comment]
fix it instead!

**Comment by TheHatMan98** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'minhook\lib\libMinHook.x64.md.140_xp.lib'	subVersion	C:\Users\user\Desktop\subVersion_2-public\subVersion_2-public\GTA internal\LINK	1
