### ISSUE TITLE
what the hell is this?

### ISSUE THREAD

**Issue by noname022** [sub1to/subVersion_2#4]
was zur hölle is das? weder eine Anleitung noch eine subversion.dll die man injecten kann
keine Ahnung was du gemacht hast aber es war sinnlos

**Comment by Schrubbdiwupp** [comment]
Das ist der Quellcode.... Keine dll bzw binary... Den reinen Code kannst du selbst bearbeiten und mit zb visual studio zur dll machen.... Wenn du dabei Hilfe brauchst helfe ich dir gerne.... Bin selber deutsch und beiss mich dadurch
