### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by InterXellar** [sub1to/subVersion_2#5]
So i know this sounds really stupid and i'm sorry sub1to, but where can i find this file "libMinHook.x64.md.140_xp.lib" i got all the minhook libs and changed the typeset to multibyte, but i cant find this file anywhere so can you please help me?

**Comment by TheHatMan98** [comment]
I have same error too... i can't find it

**Comment by sub1to** [comment]
Download the minhook source, configure the project (and compiler) appropriately and compile your own lib.
